services:
  - type: web
    name: neptune-corporate
    runtime: docker
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false" 
